name:          NAU Front End Code Guide (Beta)
description:   Standards for developing flexible, durable, and sustainable HTML and CSS.
url:           http://naustudio.github.io/code-guide

permalink:     pretty
markdown:      kramdown
highlighter:   rouge
